[package]
name = "freitunit"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
serde-xml-rs = "0.6.0"
serde_json = "1.0.120"
simple-xml-builder = "1.1.0"
